/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kvdb_connection_DBConnectionBase */

#ifndef _Included_com_kvdb_connection_DBConnectionBase
#define _Included_com_kvdb_connection_DBConnectionBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeOpen
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeExecute
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeExecute
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeDestroy
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeDestroy
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativePrepare
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_kvdb_connection_DBConnectionBase_nativePrepare
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeReset
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeReset
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeHolderCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeHolderCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeIsReadOnly
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeIsReadOnly
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeGetColumns
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeGetColumns
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativePut
 * Signature: (JLjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_com_kvdb_connection_DBConnectionBase_nativePut
  (JNIEnv *, jobject, jlong, jstring, jbyteArray);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativePutString
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_kvdb_connection_DBConnectionBase_nativePutString
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativePutShort
 * Signature: (JLjava/lang/String;S)V
 */
JNIEXPORT void JNICALL Java_com_kvdb_connection_DBConnectionBase_nativePutShort
  (JNIEnv *, jobject, jlong, jstring, jshort);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativePutInt
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_kvdb_connection_DBConnectionBase_nativePutInt
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativePutBoolean
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_kvdb_connection_DBConnectionBase_nativePutBoolean
  (JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativePutDouble
 * Signature: (JLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_kvdb_connection_DBConnectionBase_nativePutDouble
  (JNIEnv *, jobject, jlong, jstring, jdouble);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativePutFloat
 * Signature: (JLjava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_com_kvdb_connection_DBConnectionBase_nativePutFloat
  (JNIEnv *, jobject, jlong, jstring, jfloat);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativePutLong
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_kvdb_connection_DBConnectionBase_nativePutLong
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeDelete
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeDelete
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeGetBytes
 * Signature: (JLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeGetBytes
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeGet
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeGet
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeGetShort
 * Signature: (JLjava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeGetShort
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeGetInt
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeGetInt
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeGetBoolean
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeGetBoolean
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeGetDouble
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeGetDouble
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeGetLong
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeGetLong
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeGetFloat
 * Signature: (JLjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeGetFloat
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeExists
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeExists
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeCountKeys
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jlong JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeCountKeys
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_kvdb_connection_DBConnectionBase
 * Method:    nativeExecuteForResult
 * Signature: (JLjava/lang/String;)[[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_kvdb_connection_DBConnectionBase_nativeExecuteForResult
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
